PRAGMA foreign_keys = ON;
ALTER TABLE missions ADD COLUMN prompt_object_key TEXT;
ALTER TABLE missions ADD COLUMN idempotency_key TEXT;
CREATE UNIQUE INDEX ux_missions_owner_idempotency ON missions(user_id,idempotency_key);
ALTER TABLE runs ADD COLUMN correlation_id TEXT;
ALTER TABLE runs ADD COLUMN latest_sequence INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN checkpoint_id TEXT;
CREATE UNIQUE INDEX ux_runs_correlation ON runs(correlation_id);
CREATE INDEX idx_runs_active ON runs(organization_id,status,updated_at);
CREATE INDEX idx_sessions_history ON sessions(user_id,updated_at DESC);
ALTER TABLE attempts RENAME TO task_attempts;
CREATE TABLE runner_leases (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), token_hash TEXT NOT NULL UNIQUE, github_run_id TEXT NOT NULL, workflow_ref TEXT NOT NULL, expires_at INTEGER NOT NULL, revoked_at INTEGER, replaced_by TEXT, created_at INTEGER NOT NULL);
CREATE UNIQUE INDEX ux_runner_workflow ON runner_leases(run_id,github_run_id);
CREATE INDEX idx_runner_expiry ON runner_leases(expires_at,revoked_at);
CREATE TABLE run_commands (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), user_id TEXT REFERENCES users(id), type TEXT NOT NULL, payload_json TEXT NOT NULL, idempotency_key TEXT NOT NULL, created_at INTEGER NOT NULL, acknowledged_at INTEGER, acknowledgement_id TEXT, UNIQUE(run_id,idempotency_key), UNIQUE(acknowledgement_id));
CREATE INDEX idx_commands_pending ON run_commands(run_id,acknowledged_at,created_at);
CREATE TABLE permission_requests (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), capability TEXT NOT NULL, proposed_action TEXT NOT NULL, risk TEXT NOT NULL, affected_resource TEXT NOT NULL, expires_at INTEGER NOT NULL, reusable INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE permission_decisions (id TEXT PRIMARY KEY, request_id TEXT NOT NULL REFERENCES permission_requests(id), run_id TEXT NOT NULL REFERENCES runs(id), user_id TEXT NOT NULL REFERENCES users(id), decision TEXT NOT NULL, idempotency_key TEXT NOT NULL, created_at INTEGER NOT NULL, UNIQUE(request_id), UNIQUE(run_id,idempotency_key));
CREATE INDEX idx_approval_queue ON permission_requests(run_id,status,expires_at);
CREATE TABLE artifact_metadata (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), object_key TEXT NOT NULL UNIQUE, kind TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes INTEGER NOT NULL, checksum TEXT NOT NULL, retention_until INTEGER, created_at INTEGER NOT NULL);
CREATE TABLE model_calls (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), task_id TEXT, provider TEXT NOT NULL, model TEXT NOT NULL, context_limit INTEGER NOT NULL, capabilities_json TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE usage_ledger (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), model_call_id TEXT REFERENCES model_calls(id), input_tokens INTEGER NOT NULL, output_tokens INTEGER NOT NULL, cost_usd REAL NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE commits (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), sha TEXT NOT NULL, branch TEXT NOT NULL, title TEXT NOT NULL, created_at INTEGER NOT NULL, UNIQUE(run_id,sha));
CREATE TABLE pull_requests (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), provider_id TEXT NOT NULL, number INTEGER NOT NULL, url TEXT NOT NULL, status TEXT NOT NULL, approved_at INTEGER, created_at INTEGER NOT NULL, UNIQUE(provider_id,number));
CREATE TABLE encrypted_credential_references (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(id), kind TEXT NOT NULL, encrypted_object_key TEXT NOT NULL, fingerprint TEXT NOT NULL, created_at INTEGER NOT NULL, UNIQUE(organization_id,kind,fingerprint));
CREATE TABLE rate_limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at INTEGER NOT NULL);
CREATE INDEX idx_artifacts_run ON artifact_metadata(run_id,created_at);
CREATE INDEX idx_usage_run ON usage_ledger(run_id,created_at);
