import fs from "node:fs/promises"; import path from "node:path"; import crypto from "node:crypto"; import { AgentRuntime } from "./runtime.mjs";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export class RunnerSupervisor {
 constructor(options={}){this.origin=options.origin||process.env.CONTROL_PLANE_ORIGIN;this.runId=options.runId||process.env.RUN_ID;this.correlationId=options.correlationId||process.env.CORRELATION_ID;this.fetch=options.fetch||fetch;this.lease=null;this.stopped=false;this.sequence=0;this.idleMs=options.idleMs||Number(process.env.WARM_IDLE_MS||180000);this.started=Date.now();}
 async oidc(){const url=process.env.ACTIONS_ID_TOKEN_REQUEST_URL,token=process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN;if(!url||!token)throw Error("GitHub OIDC environment unavailable");const r=await this.fetch(`${url}&audience=${encodeURIComponent(process.env.OIDC_AUDIENCE||"avos-runner")}`,{headers:{authorization:`Bearer ${token}`}});if(!r.ok)throw Error("Unable to obtain GitHub OIDC token");return (await r.json()).value;}
 async register(){const oidcToken=await this.oidc();const r=await this.fetch(`${this.origin}/api/runner/register`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({schemaVersion:1,runId:this.runId,correlationId:this.correlationId,githubRunId:process.env.GITHUB_RUN_ID,oidcToken})});if(!r.ok)throw Error(`Runner registration failed (${r.status})`);this.lease=await r.json();}
 async api(route,init={}){const r=await this.fetch(`${this.origin}${route}`,{...init,headers:{...init.headers,authorization:`Bearer ${this.lease.token}`}});if(!r.ok)throw Error(`Control plane ${route} failed (${r.status})`);return r;}
 async emit(eventType,payload,agentId="runner"){this.sequence++;await this.api("/api/runner/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({events:[{schemaVersion:1,eventId:`evt_${crypto.randomUUID().replaceAll("-","")}`,sequence:this.sequence,runId:this.runId,agentId,eventType,timestamp:new Date().toISOString(),payload}]})});}
 async checkpoint(runtime){const dir=path.resolve(process.env.WORKSPACE_DIR||".",".agent");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"checkpoint.json"),JSON.stringify(runtime.checkpoint(process.env.GITHUB_SHA||"unknown"),null,2));await this.emit("checkpoint_saved",{path:".agent/checkpoint.json"});}
 async commands(runtime){const rows=await (await this.api("/api/runner/commands")).json();for(const c of rows){const p=JSON.parse(c.payload_json);if(c.type==="cancel"){this.stopped=true;runtime.cancel()}else if(c.type==="interrupt")runtime.interrupt(p.guidance);else if(c.type==="permission_decision")runtime.emit("permission-decision",p);else if(c.type==="release_runner")this.stopped=true;await this.api("/api/runner/ack",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({commandId:c.id,acknowledgementId:`ack_${crypto.randomUUID()}`})});}}
 async warm(runtime){const deadline=Date.now()+this.idleMs;let wait=1000;while(!this.stopped&&Date.now()<deadline){await this.commands(runtime);await sleep(wait);wait=Math.min(15000,Math.round(wait*1.7));}await this.checkpoint(runtime);}
 async start({mission,execute}){await this.register();await this.emit("checkout",{summary:"Workspace ready"});const runtime=new AgentRuntime({mission,modelCapability:{contextWindow:128000,maxOutputTokens:8192,safeReservePercent:20},execute});runtime.on("progress",p=>this.emit("progress",p));runtime.on("permission-request",p=>this.emit("permission_request",p));await runtime.run({id:"root",mission});await this.checkpoint(runtime);if(!this.stopped){await this.emit("warm_idle",{summary:"Runner retained briefly; execution time is being consumed"});await this.warm(runtime)}await this.emit(this.stopped?"cancelled":"completed",{summary:this.stopped?"Cancelled and cleaned up":"Run completed"});}
}
if(import.meta.url===`file://${process.argv[1]}`){const supervisor=new RunnerSupervisor();const mission={checksum:process.env.MISSION_CHECKSUM||"mission_runtime",successCriteria:[]};const shutdown=()=>{supervisor.stopped=true};process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);supervisor.start({mission,execute:async()=>({summary:"Runtime turn complete"})}).catch(async e=>{try{await supervisor.emit("failed",{message:String(e).replace(/Bearer\\s+\\S+/g,"Bearer [REDACTED]")})}finally{process.exitCode=1}});}
