import fs from"node:fs/promises";import path from"node:path";import crypto from"node:crypto";import{spawn}from"node:child_process";import{execFile}from"node:child_process";import{promisify}from"node:util";import{AgentRuntime}from"./runtime.mjs";const exec=promisify(execFile),sleep=ms=>new Promise(r=>setTimeout(r,ms));
export class RunnerSupervisor{
 constructor(o={}){this.origin=o.origin||process.env.CONTROL_PLANE_ORIGIN;this.runId=o.runId||process.env.RUN_ID;this.correlationId=o.correlationId||process.env.CORRELATION_ID;this.fetch=o.fetch||fetch;this.lease=null;this.stopped=false;this.sequence=0;this.idleMs=o.idleMs||Number(process.env.WARM_IDLE_MS||180000);this.refreshing=null;this.child=null}
 async oidc(){const u=process.env.ACTIONS_ID_TOKEN_REQUEST_URL,t=process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN;if(!u||!t)throw Error("GitHub OIDC environment unavailable");const r=await this.fetch(`${u}&audience=${encodeURIComponent(process.env.OIDC_AUDIENCE||"avos-runner")}`,{headers:{authorization:`Bearer ${t}`}});if(!r.ok)throw Error("Unable to obtain GitHub OIDC token");return(await r.json()).value}
 async register(){const r=await this.fetch(`${this.origin}/api/runner/register`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({schemaVersion:1,runId:this.runId,correlationId:this.correlationId,githubRunId:process.env.GITHUB_RUN_ID,oidcToken:await this.oidc()})});if(!r.ok)throw Error(`Runner registration failed (${r.status})`);this.lease=await r.json()}
 async refresh(){if(this.refreshing)return this.refreshing;this.refreshing=(async()=>{const old=this.lease.token,r=await this.fetch(`${this.origin}/api/runner/heartbeat`,{method:"POST",headers:{authorization:`Bearer ${old}`,"content-type":"application/json"},body:JSON.stringify({runId:this.runId})});if(!r.ok)throw Error(`Lease refresh failed (${r.status})`);const x=await r.json();this.lease={...this.lease,token:x.token,expiresAt:x.expiresAt}})().finally(()=>this.refreshing=null);return this.refreshing}
 async api(route,init={}){if(this.lease.expiresAt&&Date.parse(this.lease.expiresAt)-Date.now()<90000)await this.refresh();const r=await this.fetch(`${this.origin}${route}`,{...init,headers:{...init.headers,authorization:`Bearer ${this.lease.token}`}});if(!r.ok)throw Error(`Control plane ${route} failed (${r.status})`);return r}
 async document(route,attempts=6){let delay=250;for(let i=0;i<attempts;i++){const r=await this.fetch(`${this.origin}${route}`,{headers:{authorization:`Bearer ${this.lease.token}`}});if(r.ok||r.status!==503)return r;await sleep(delay);delay=Math.min(4000,delay*2)}throw Error(`Document ${route} remained unavailable after bounded retries`)}
 async emit(eventType,payload,agentId="runner"){await this.api("/api/runner/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({events:[{schemaVersion:1,eventId:`evt_${crypto.randomUUID().replaceAll("-","")}`,localSequence:++this.sequence,runId:this.runId,agentId,eventType,timestamp:new Date().toISOString(),payload}]})})}
 async checkpoint(runtime){const dir=path.resolve(process.env.WORKSPACE_DIR||".",".agent"),data=JSON.stringify(runtime.checkpoint(process.env.STARTING_COMMIT||"unknown"),null,2);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"checkpoint.json"),data);await this.api("/api/runner/checkpoints",{method:"POST",headers:{"content-type":"application/json","x-repository-revision":process.env.STARTING_COMMIT||"unknown"},body:data});await this.emit("checkpoint_saved",{summary:"Remote checkpoint persisted"})}
 async commands(runtime){const rows=await(await this.api("/api/runner/commands")).json();for(const c of rows){const p=JSON.parse(c.payload_json);if(c.type==="cancel"){this.stopped=true;runtime.cancel();this.child?.kill("SIGTERM")}else if(c.type==="interrupt")runtime.interrupt(p.guidance);else if(c.type==="permission_decision")runtime.emit("permission-decision",p);else if(c.type==="follow_up"){runtime.interrupt(p.message||p.guidance);await runtime.run({id:c.id,amendment:p})}else if(c.type==="release_runner")this.stopped=true;await this.api("/api/runner/ack",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({commandId:c.id})})}}
 async warm(runtime){const end=Date.now()+this.idleMs;let delay=1000;while(!this.stopped&&Date.now()<end){await this.commands(runtime);await sleep(delay);delay=Math.min(15000,Math.round(delay*1.7))}await this.checkpoint(runtime)}
 async start({mission,execute}){if(!this.lease)await this.register();const runtime=new AgentRuntime({mission,modelCapability:{contextWindow:128000,maxOutputTokens:8192,safeReservePercent:20},execute});runtime.on("progress",x=>void this.emit("progress",x));runtime.on("permission-request",x=>void this.api("/api/runner/permissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(x)}));await runtime.run({id:"root",mission});await this.checkpoint(runtime);if(!this.stopped){await this.emit("warm_idle",{summary:"Runner retained briefly; GitHub Actions time is being consumed"});await this.warm(runtime)}return runtime}
}
async function main(){const s=new RunnerSupervisor();await s.register();const m=await(await s.api("/api/runner/mission")).json(),promptResponse=await s.document(m.prompt.url),prompt=await promptResponse.text();if(crypto.createHash("sha256").update(prompt).digest("hex")!==m.checksum)throw Error("Mission prompt checksum mismatch");const workspace=path.resolve(process.env.WORKSPACE_DIR||"workspace");await fs.rm(workspace,{recursive:true,force:true});const credential=await(await s.api("/api/runner/credentials/repository",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({repository:m.repository})})).json();await exec("git",["clone","--depth","1","--branch",m.branch,`https://x-access-token:${credential.token}@github.com/${m.repository}.git`,workspace],{env:{...process.env,GIT_TERMINAL_PROMPT:"0"}});await exec("git",["remote","set-url","origin",`https://github.com/${m.repository}.git`],{cwd:workspace});process.env.WORKSPACE_DIR=workspace;process.env.TARGET_REPO=m.repository;process.env.TARGET_BRANCH=m.branch;process.env.USER_PROMPT=prompt;process.env.STARTING_COMMIT=(await exec("git",["rev-parse","HEAD"],{cwd:workspace})).stdout.trim();const restored=await s.document("/api/runner/checkpoint");if(restored.status!==204){const checkpoint=await restored.json();if(checkpoint.schemaVersion!==1||checkpoint.missionRef!==m.checksum||checkpoint.repositoryRevision!==process.env.STARTING_COMMIT)throw Error("Remote checkpoint validation failed")}await s.emit("checkout",{summary:"Target repository checked out",startingCommit:process.env.STARTING_COMMIT});const execute=()=>new Promise((resolve,reject)=>{s.child=spawn(process.execPath,[path.resolve("packages/agent-runtime/src",m.specification.executionMode==="swarm"?"swarm.mjs":"agent.mjs")],{stdio:"inherit",env:process.env});s.child.once("exit",c=>c===0?resolve({summary:"Real agent loop completed"}):reject(Error(`Agent loop exited ${c}`)))}),runtime=await s.start({mission:{checksum:m.checksum,successCriteria:m.specification.requirements||[]},execute});await s.api("/api/runner/finalize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status:s.stopped?"cancelled":"completed",summary:s.stopped?"Cancelled":"Completed"})});return runtime}
if(import.meta.url===`file://${process.argv[1]}`)main().catch(e=>{console.error(String(e).replace(/https:\/\/[^@]+@/g,"https://[REDACTED]@"));process.exitCode=1});
