import type{Env}from"../types";import{randomId,sha256}from"../security";import{ApiError}from"../middleware/errors";
export type DocumentType="prompt"|"attachment"|"checkpoint"|"transcript";
export type DocumentRecord={id:string;kv_key:string;content_type:string;size_bytes:number;checksum:string;owner_id:string;mission_id?:string;run_id?:string;created_at:number;expires_at?:number;document_type:DocumentType;state:"pending"|"available"|"rejected"};
const day=()=>new Date().toISOString().slice(0,10),limit=(v:string|undefined,d:number)=>Number(v||d);
async function countWrite(env:Env){const cap=limit(env.MAX_KV_WRITES_PER_DAY,800),key=`kv_writes:${day()}`;const row=await env.DB.prepare("SELECT value FROM usage_counters WHERE key=?").bind(key).first<any>();if(env.FREE_ONLY_MODE!=="false"&&Number(row?.value||0)>=cap)throw new ApiError(429,"free_quota_reached",`Estimated daily KV write limit (${cap}) reached. Existing documents remain readable; no charge occurred.`);await env.DB.prepare("INSERT INTO usage_counters(key,value,updated_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET value=value+1,updated_at=excluded.updated_at").bind(key,Date.now()).run()}
async function put(env:Env,r:Omit<DocumentRecord,"state">,value:ArrayBuffer|string){await countWrite(env);await env.DOCUMENTS.put(r.kv_key,value,{expiration:r.expires_at?Math.floor(r.expires_at/1000):undefined});await env.DB.prepare("INSERT INTO documents(id,kv_key,content_type,size_bytes,checksum,owner_id,mission_id,run_id,created_at,expires_at,document_type,state) VALUES(?,?,?,?,?,?,?,?,?,?,?,'pending')").bind(r.id,r.kv_key,r.content_type,r.size_bytes,r.checksum,r.owner_id,r.mission_id||null,r.run_id||null,r.created_at,r.expires_at||null,r.document_type).run();const visible=await env.DOCUMENTS.get(r.kv_key,"arrayBuffer");if(visible&&await sha256(visible)===r.checksum)await env.DB.prepare("UPDATE documents SET state='available' WHERE id=?").bind(r.id).run();return{...r,state:visible?"available":"pending"}as DocumentRecord}
async function get(env:Env,id:string,ownerId:string,type:DocumentType,runId?:string){const r=await env.DB.prepare("SELECT * FROM documents WHERE id=? AND owner_id=? AND document_type=? AND state!='rejected' AND (expires_at IS NULL OR expires_at>?)").bind(id,ownerId,type,Date.now()).first<DocumentRecord>();if(!r||runId&&r.run_id!==runId)throw new ApiError(404,"document_not_found","Document is unavailable or not authorized for this run.");const bytes=await env.DOCUMENTS.get(r.kv_key,"arrayBuffer");if(!bytes)throw new ApiError(503,"document_not_visible","Document propagation is pending; retry with bounded exponential backoff.");if(bytes.byteLength!==r.size_bytes||await sha256(bytes)!==r.checksum)throw new ApiError(502,"document_integrity_failed","Stored document failed checksum validation.");if(r.state!=="available")await env.DB.prepare("UPDATE documents SET state='available' WHERE id=?").bind(r.id).run();return{record:{...r,state:"available"},bytes}}
export async function putPrompt(env:Env,ownerId:string,missionId:string,prompt:string){const bytes=new TextEncoder().encode(prompt),checksum=await sha256(bytes.buffer as ArrayBuffer),id=randomId("document");return put(env,{id,kv_key:`owner/${ownerId}/missions/${missionId}/prompt`,content_type:"text/plain; charset=utf-8",size_bytes:bytes.byteLength,checksum,owner_id:ownerId,created_at:Date.now(),document_type:"prompt"},bytes.buffer as ArrayBuffer)}
export const getPrompt=(env:Env,id:string,ownerId:string)=>get(env,id,ownerId,"prompt");
export async function putAttachment(env:Env,ownerId:string,id:string,data:ArrayBuffer,contentType:string,expiresAt?:number){return put(env,{id,kv_key:`owner/${ownerId}/attachments/${id}/content`,content_type:contentType,size_bytes:data.byteLength,checksum:await sha256(data),owner_id:ownerId,created_at:Date.now(),expires_at:expiresAt,document_type:"attachment"},data)}
export const getAttachment=(env:Env,id:string,ownerId:string)=>get(env,id,ownerId,"attachment");
export async function putCheckpoint(env:Env,ownerId:string,runId:string,id:string,data:ArrayBuffer){return put(env,{id,kv_key:`owner/${ownerId}/runs/${runId}/checkpoints/${id}`,content_type:"application/json",size_bytes:data.byteLength,checksum:await sha256(data),owner_id:ownerId,run_id:runId,created_at:Date.now(),document_type:"checkpoint"},data)}
export const getCheckpoint=(env:Env,id:string,ownerId:string,runId:string)=>get(env,id,ownerId,"checkpoint",runId);
export async function putTranscript(env:Env,ownerId:string,runId:string,data:ArrayBuffer){const id=randomId("transcript");return put(env,{id,kv_key:`owner/${ownerId}/runs/${runId}/transcript`,content_type:"application/json",size_bytes:data.byteLength,checksum:await sha256(data),owner_id:ownerId,run_id:runId,created_at:Date.now(),document_type:"transcript"},data)}
export const getTranscript=(env:Env,id:string,ownerId:string,runId:string)=>get(env,id,ownerId,"transcript",runId);
export async function headDocument(env:Env,id:string,ownerId:string){return env.DB.prepare("SELECT id,content_type,size_bytes,checksum,created_at,expires_at,document_type,state FROM documents WHERE id=? AND owner_id=?").bind(id,ownerId).first<DocumentRecord>()}
export async function deleteRunDocuments(env:Env,runId:string,ownerId:string){const rows=await env.DB.prepare("SELECT id,kv_key FROM documents WHERE run_id=? AND owner_id=?").bind(runId,ownerId).all<any>();await Promise.all(rows.results.map(r=>env.DOCUMENTS.delete(r.kv_key)));await env.DB.prepare("DELETE FROM documents WHERE run_id=? AND owner_id=?").bind(runId,ownerId).run();return rows.results.length}
