import { z } from "zod";

export const PROTOCOL_VERSION = 1 as const;
const id = z.string().min(8).max(160);
const timestamp = z.string().datetime();
const json = z.unknown();
export const RunStatus = z.enum(["queued","provisioning","runner_booting","checkout","planning","executing","waiting_for_approval","verifying","publishing","warm_idle","cancelling","cancelled","completed","failed","recovery_required"]);
export const TaskStatus = z.enum(["pending","ready","running","blocked","waiting_for_approval","verifying","completed","failed","cancelled"]);
export const Run = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,userId:id,organizationId:id,missionId:id,sessionId:id,repositoryId:id,status:RunStatus,latestSequence:z.number().int().nonnegative(),createdAt:timestamp,updatedAt:timestamp});
export const Task = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,runId:id,status:TaskStatus,dependencies:z.array(id),packet:json,attempt:z.number().int().nonnegative()});
export const RunCommand = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,runId:id,type:z.enum(["cancel","interrupt","follow_up","permission_decision","release_runner"]),idempotencyKey:id,payload:json,createdAt:timestamp,acknowledgedAt:timestamp.nullable().default(null)});
export const RunEvent = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),eventId:id,sequence:z.number().int().positive(),runId:id,taskId:id.nullable().optional(),attemptId:id.nullable().optional(),agentId:id,eventType:z.string().min(1).max(80),timestamp,payload:json});
export const Checkpoint = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,runId:id,missionRef:id,objectKey:z.string().min(1),checksum:id,repositoryRevision:z.string().min(1),createdAt:timestamp,retains:z.array(z.enum(["mission","amendments","task","criteria","instructions","plan","files","tests","failures","approval","next_action"]))});
export const PermissionRequest = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,runId:id,capability:z.string().min(1),proposedAction:z.string().min(1),risk:z.string().min(1),resource:z.string().min(1),expiresAt:timestamp,reusable:z.boolean()});
export const PermissionDecision = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,requestId:id,runId:id,decision:z.enum(["allow","deny"]),idempotencyKey:id,decidedAt:timestamp});
export const Attachment = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,ownerId:id,filename:z.string().min(1).max(255),mimeType:z.string().min(1),size:z.number().int().nonnegative(),checksum:id,objectKey:z.string().min(1),scanStatus:z.enum(["pending","validated","rejected"])});
export const PromptReference = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,objectKey:z.string().min(1),checksum:id,size:z.number().int().positive(),sections:z.array(z.object({id,offset:z.number().int().nonnegative(),length:z.number().int().positive(),requirements:z.array(z.string())}))});
export const RunnerRegistration = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),runId:id,oidcToken:z.string().min(20),githubRunId:z.string().min(1),correlationId:id});
export const RunnerHeartbeat = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),runId:id,leaseToken:z.string().min(20),sequence:z.number().int().nonnegative(),remainingJobSeconds:z.number().int().nonnegative(),timestamp});
export const RunnerLease = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,runId:id,token:z.string().min(20),expiresAt:timestamp,githubRunId:z.string().min(1)});
const repository=z.string().regex(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/).max(200);
export const MissionCreate=z.object({sessionId:id.optional(),prompt:z.string().min(1).max(2_097_152),repository,branch:z.string().min(1).max(255).default("main"),attachmentIds:z.array(id).max(20).default([]),requirements:z.array(z.string().max(2000)).max(100).default([]),executionMode:z.enum(["single","swarm"]).default("single"),plannerModel:z.string().max(120).optional(),workerModel:z.string().max(120).optional(),workerCount:z.number().int().min(1).max(16).default(1),tokenBudget:z.number().int().positive().max(10_000_000).optional(),createPr:z.boolean().default(true)});
export const RunDispatch=z.object({missionId:id,sessionId:id,repository,branch:z.string().min(1).max(255).default("main"),environment:z.enum(["production","preview"]).default("production")});
export const AttachmentInitiate=z.object({filename:z.string().min(1).max(255),mimeType:z.string().min(1).max(120),size:z.number().int().positive().max(20_971_520),checksum:z.string().regex(/^[a-f0-9]{64}$/i)});
export const AttachmentComplete=z.object({id:id,capability:z.string().min(32),checksum:z.string().regex(/^[a-f0-9]{64}$/i)});
export const PermissionDecisionBody=z.object({requestId:id,decision:z.enum(["allow","deny"]),reason:z.string().max(2000).optional()});
export const RunnerEvents=z.object({events:z.array(RunEvent.omit({sequence:true}).extend({sequence:z.number().int().nonnegative().optional(),localSequence:z.number().int().nonnegative().optional()})).min(1).max(100)});
export const UsageLedger = z.object({schemaVersion:z.literal(PROTOCOL_VERSION),id,runId:id,provider:z.string(),model:z.string(),inputTokens:z.number().int().nonnegative(),outputTokens:z.number().int().nonnegative(),costUsd:z.number().nonnegative(),contextLimit:z.number().int().positive(),timestamp});
export type RunEvent = z.infer<typeof RunEvent>; export type RunCommand = z.infer<typeof RunCommand>;
export function parse<T extends z.ZodTypeAny>(schema:T, value:unknown):z.infer<T>{ return schema.parse(value); }
