import type{Env}from"../types";import{ApiError}from"../middleware/errors";import{repositoryToken}from"./github";import{open,seal}from"./vault";
export async function checkoutCredential(env:Env,repository:string){return repositoryToken(env,repository)}
export const providerDefinitions={gemini:{endpoint:"https://generativelanguage.googleapis.com/v1beta/models",auth:"query"},groq:{endpoint:"https://api.groq.com/openai/v1/models",auth:"bearer"},openrouter:{endpoint:"https://openrouter.ai/api/v1/models",auth:"bearer"},cerebras:{endpoint:"https://api.cerebras.ai/v1/models",auth:"bearer"},nvidia:{endpoint:"https://integrate.api.nvidia.com/v1/models",auth:"bearer"}}as const;
export type Provider=keyof typeof providerDefinitions;
export function parseKeys(input:string){return[...new Set(input.split(",").map(x=>x.trim()).filter(Boolean))]}
export function validKey(key:string){return key.length>=16&&key.length<=512&&!/\s/.test(key)}
export async function validateProvider(provider:Provider,key:string,fetcher:typeof fetch=fetch){const d=providerDefinitions[provider],url=d.auth==="query"?`${d.endpoint}?key=${encodeURIComponent(key)}`:d.endpoint,r=await fetcher(url,{headers:d.auth==="bearer"?{authorization:`Bearer ${key}`}:{}});if(!r.ok)throw new ApiError(422,"provider_validation_failed",`The ${provider} credential could not be validated (${r.status}).`);const data=await r.json<any>(),models=(data.data||data.models||[]).slice(0,100).map((m:any)=>({id:String(m.id||m.name),contextWindow:m.context_window||m.contextWindow,plannerEligible:true,workerEligible:true}));return models}
export async function storeProvider(env:Env,provider:Provider,input:string){const keys=parseKeys(input);if(!keys.length||keys.some(k=>!validKey(k)))throw new ApiError(422,"provider_key_invalid","The credential syntax is invalid.");const validatedAt=Date.now();let models:any[]=[];for(const key of keys){models=await validateProvider(provider,key);const c=await seal(env,`provider:${provider}`,key);await env.DB.prepare("INSERT INTO encrypted_credentials(id,credential_type,provider,key_version,nonce,ciphertext,created_at,validated_at) VALUES(?,?,?,?,?,?,?,?)").bind(c.id,c.credentialType,provider,c.keyVersion,c.nonce,c.ciphertext,c.createdAt,validatedAt).run()}await env.DB.prepare("INSERT INTO provider_settings(provider,enabled,models_json,last_validated_at,created_at,updated_at) VALUES(?,1,?,?,?,?) ON CONFLICT(provider) DO UPDATE SET enabled=1,models_json=excluded.models_json,last_validated_at=excluded.last_validated_at,updated_at=excluded.updated_at").bind(provider,JSON.stringify(models),validatedAt,validatedAt,validatedAt).run();await env.DB.prepare("UPDATE setup_state SET provider_tested_at=?,updated_at=? WHERE id=1").bind(validatedAt,validatedAt).run();return{provider,configured:true,createdAt:validatedAt,lastSuccessfulValidationTime:validatedAt,models}}
export async function removeProvider(env:Env,provider:Provider){const n=Date.now();await env.DB.batch([env.DB.prepare("UPDATE encrypted_credentials SET disabled_at=? WHERE provider=? AND disabled_at IS NULL").bind(n,provider),env.DB.prepare("UPDATE provider_settings SET enabled=0,updated_at=? WHERE provider=?").bind(n,provider)]);return{provider,configured:false}}
export async function providerStatuses(env:Env){const q=await env.DB.prepare("SELECT p.*,COUNT(c.id) credential_count,MIN(c.created_at) credential_created_at FROM provider_settings p LEFT JOIN encrypted_credentials c ON c.provider=p.provider AND c.disabled_at IS NULL GROUP BY p.provider").all<any>();return q.results.map(x=>({provider:x.provider,configured:Boolean(x.enabled&&x.credential_count),createdAt:x.credential_created_at,lastSuccessfulValidationTime:x.last_validated_at,models:JSON.parse(x.models_json),freeOnlyWarning:"Confirm provider pricing and quotas before use."}))}
export async function providerCredential(env:Env,provider:Provider){const setting=await env.DB.prepare("SELECT enabled FROM provider_settings WHERE provider=?").bind(provider).first<any>(),row=await env.DB.prepare("SELECT * FROM encrypted_credentials WHERE provider=? AND disabled_at IS NULL ORDER BY validated_at DESC LIMIT 1").bind(provider).first<any>();if(!setting?.enabled||!row)throw new ApiError(409,"provider_unavailable","The selected provider is not enabled.");return open(env,row)}
