import type{Env}from"../types";import{ApiError}from"../middleware/errors";import{open}from"./vault";
const b64=(v:Uint8Array|string)=>btoa(typeof v==="string"?v:String.fromCharCode(...v)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
let cached:{token:string;expires:number}|undefined;
async function configuration(env:Env){const s=await env.DB.prepare("SELECT github_app_id,github_client_id,github_installation_id FROM setup_state WHERE id=1").first<any>();if(!s?.github_app_id)throw new ApiError(409,"github_app_required","Connect the deployment GitHub App first.");const rows=await env.DB.prepare("SELECT * FROM encrypted_credentials WHERE credential_type IN ('github_private_key','github_client_secret') AND disabled_at IS NULL ORDER BY created_at DESC").all<any>(),values:any={};for(const r of rows.results)if(!values[r.credential_type])values[r.credential_type]=await open(env,r);return{...s,privateKey:values.github_private_key,clientSecret:values.github_client_secret}}
async function appJwt(env:Env){const cfg=await configuration(env),pem=cfg.privateKey.replace(/\\n/g,"\n"),der=Uint8Array.from(atob(pem.replace(/-----(BEGIN|END) (RSA )?PRIVATE KEY-----|\s/g,"")),c=>c.charCodeAt(0)),key=await crypto.subtle.importKey("pkcs8",der,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),now=Math.floor(Date.now()/1000),head=b64(JSON.stringify({alg:"RS256",typ:"JWT"})),body=b64(JSON.stringify({iat:now-30,exp:now+540,iss:cfg.github_app_id})),sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(`${head}.${body}`));return`${head}.${body}.${b64(new Uint8Array(sig))}`}
async function github(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{accept:"application/vnd.github+json","user-agent":"AVOS-ControlPlane","x-github-api-version":"2022-11-28",...init.headers}});if(!r.ok)throw new ApiError(502,"github_error",`GitHub rejected the request (${r.status}).`);return r}
export async function installationToken(env:Env,repositories?:string[]){if(!repositories?.length&&cached&&cached.expires>Date.now()+60000)return cached.token;const jwt=await appJwt(env),r=await github(`https://api.github.com/app/installations/${(await configuration(env)).github_installation_id}/access_tokens`,{method:"POST",headers:{authorization:`Bearer ${jwt}`,"content-type":"application/json"},body:repositories?.length?JSON.stringify({repositories}):undefined}),x=await r.json<any>();if(!repositories?.length)cached={token:x.token,expires:Date.parse(x.expires_at)};return x.token}
export async function dispatch(env:Env,inputs:Record<string,string>){const token=await installationToken(env);await github(`https://api.github.com/repos/${env.CONTROL_REPOSITORY}/actions/workflows/agent.yml/dispatches`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({ref:env.CONTROL_REPOSITORY_DEFAULT_BRANCH||"main",inputs})})}
export async function cancelWorkflow(env:Env,workflowRunId:string){const token=await installationToken(env);await github(`https://api.github.com/repos/${env.CONTROL_REPOSITORY}/actions/runs/${workflowRunId}/cancel`,{method:"POST",headers:{authorization:`Bearer ${token}`}})}
export async function repositoryToken(env:Env,repository:string){const allowed=(env.REPOSITORY_ALLOWLIST||"").split(",").map(x=>x.trim()).filter(Boolean);if(allowed.length&&!allowed.includes(repository))throw new ApiError(403,"repository_not_allowed","This repository is not in the deployment allowlist.");const [owner,name]=repository.split("/");const token=await installationToken(env,[name]);await github(`https://api.github.com/repos/${owner}/${name}`,{headers:{authorization:`Bearer ${token}`}});return{token,repository,expiresIn:3300}}
export async function oauthExchange(env:Env,code:string){const cfg=await configuration(env),r=await fetch("https://github.com/login/oauth/access_token",{method:"POST",headers:{accept:"application/json","content-type":"application/json"},body:JSON.stringify({client_id:cfg.github_client_id,client_secret:cfg.clientSecret,code})});if(!r.ok)throw new ApiError(502,"oauth_exchange_failed","GitHub sign-in could not be completed.");const x=await r.json<any>();if(!x.access_token)throw new ApiError(401,"oauth_denied","GitHub sign-in was denied.");return x.access_token}
export async function oauthUser(token:string){const r=await github("https://api.github.com/user",{headers:{authorization:`Bearer ${token}`}});return r.json<any>()}
